### ISSUE TITLE
"File Type Not Supported" on Export and Import Quiz

### ISSUE THREAD

**Issue by aragonense** [themeum/tutor#16]
When exporting and then importing a Quiz, I am receiving the following message in the Browser. "File Type Not Supported".

quiz-import-export.js
![tutor](https://user-images.githubusercontent.com/982084/83538842-afec3d00-a4cc-11ea-848b-c0e8a38a3649.png)
![tutor2](https://user-images.githubusercontent.com/982084/83538846-b084d380-a4cc-11ea-9087-9de4133c2084.png)

is there any specific encoding of the CSV file ??

**Comment by laharika** [comment]
For Chrome browsers in a windows system, file type for CSV files could be `application/octet-stream` or `application/vnd.ms-excel`, whereas for mac, it's always `text/csv`.

**Comment by aragonense** [comment]
> For Chrome browsers in a windows system, file type for CSV files could be `application/octet-stream` or `application/vnd.ms-excel`, whereas for mac, it's always `text/csv`.

Thanks for the quick response. It would be interesting to include a condition in JS that detects this type of detail. stays as a Suggestion.

**Comment by aragonense** [comment]
As a temporary solution, I removed this condition from JS. I hope not to impact the general functioning.

**Comment by jayedul** [comment]
Frontend validation has been removed already. Now it uses backend side validation.
