### ISSUE TITLE
Broken Layout: incompatibility with GeneratePress?

### ISSUE THREAD

**Issue by 360fun** [themeum/tutor#18]
![image](https://user-images.githubusercontent.com/844090/84281909-6b4e4a80-ab39-11ea-9d2c-cbc20c4ecac4.png)

**Comment by 360fun** [comment]
temporary (dirty) fix:

jQuery(document).ready(function($) {
$('#content .tutor-row .tutor-col-9').removeClass('tutor-col-9').addClass('tutor-col-8');
});

**Comment by lesthertod** [comment]
It also affects the Single Course page.
Adding to the temporary fix:

`jQuery(document).ready(function($) {
  $('#content .tutor-row .tutor-col-9').removeClass('tutor-col-9').addClass('tutor-col-8');
  $('#content .tutor-wrap .tutor-container .tutor-row .tutor-col-8').removeClass('tutor-col-8').addClass('tutor-col-7');
});`
