### ISSUE TITLE
Admin user enrolled instead student when payment status is switched manually (EDD)

### ISSUE THREAD

**Issue by 360fun** [themeum/tutor#20]
1. student buys a course
2. EDD receives the payment and put it in pending status (I use [Sorsawo EDD Bank Transfer](https://wordpress.org/plugins/sorsawodigital-edd-bank-transfer/))
3. Admin switch the payment on Complete (value='publish') (when receives the money in the bank)
4. Admin is enrolled instead of the student (BUG)

**DEBUGGING**
This seems to be the problem:
tutor_utils()->do_enroll($course_id, $payment_id);

Should pass also **$user_id** somehow, otherwise **get_user_id** calls **get_current_user_id()** which loads the current user id (the Admin) instead of the student id.

**Comment by 360fun** [comment]
I patched **edd_update_payment_status** in this way, waiting the official fix:

```
	public function edd_update_payment_status($payment_id, $new_status, $old_status ){
		if ($new_status !== 'publish'){
			return;
		}

		$payment = new \EDD_Payment( $payment_id );
		$cart_details   = $payment->cart_details;		
		$user_id        = $payment->user_info['id'];

		if ( is_array( $cart_details ) ) {
			foreach ( $cart_details as $cart_index => $download ) {

				$if_has_course = tutor_utils()->product_belongs_with_course($download['id']);
				if ($if_has_course){
					$course_id = $if_has_course->post_id;
					$has_any_enrolled = tutor_utils()->has_any_enrolled($course_id);
					if ( ! $has_any_enrolled){
						tutor_utils()->do_enroll($course_id, $payment_id, $user_id);
					}
				}
			}
			tutor_utils()->complete_course_enroll($payment_id);
		}

	}
```

**Comment by sksaju** [comment]
Hey @360fun your pull request has been merged! thanks for your contribution

**Comment by 360fun** [comment]
Awesome! Thank you 🥳
