### ISSUE TITLE
Maximum Students doesn't work

### ISSUE THREAD

**Issue by GabrielHenriqueRS** [themeum/tutor#23]
I created a course and set the maximum students to 2. I tested creating the enrollments manually and by add-on, but neither works. I inserted an image demonstrating this bug.
![max-students-bug](https://user-images.githubusercontent.com/38798917/85809062-1b70a580-b72d-11ea-8f6c-5e2c6594176f.png)

**Comment by belisards** [comment]
Hey, any update about this issue?

**Comment by sksaju** [comment]
This problem will no longer exist from next release, thanks

**Comment by belisards** [comment]
Thanks! Do you know when it will be available?

Em sáb, 11 de jul de 2020 12:29, Shazahan Kabir Saju <
notifications@github.com> escreveu:

**Comment by sksaju** [comment]
This issue is fixed with new update. thanks
