### ISSUE TITLE
emails not sending

### ISSUE THREAD

**Issue by zacinaction** [themeum/tutor#25]

**Comment by sksaju** [comment]
Please let me know your issue with more details.

**Comment by Shietnar** [comment]
The file you are trying to load is not exists in your theme or tutor plugins location, if you are a developer and extending tutor plugin, please create a php file at location /home/

**Comment by zacinaction** [comment]
Chutiye ho? 2020 mai mail kia th or tum abhi reply kr rhe

**Comment by sksaju** [comment]
Hi, @zacinaction

Since you are not providing any details regarding your issue. I've to close this issue now, thanks
