### ISSUE TITLE
Tutor instructor profile picture isn't saving/ showing after updating profile

### ISSUE THREAD

**Issue by webangon** [themeum/tutor#37]
There is issue with tutor avatar.
1. It's not showing, it seems tutor avatar is not working, there is no meta value saved.

![download](https://user-images.githubusercontent.com/7946657/102853773-30fc2900-444b-11eb-9278-69a770a90b91.png)

2. For this reason tutor avatar is not working, just displaying letters.
 
![download](https://user-images.githubusercontent.com/7946657/102853917-86383a80-444b-11eb-959c-45ab1d90ee46.png)

**Comment by ecastanedapl** [comment]
#50 

I just send the lines to fix the problem.

**Comment by sksaju** [comment]
This issue has been resolved in v1.8.6, thanks
