### ISSUE TITLE
Questions about TutorLMS

### ISSUE THREAD

**Issue by PROgramJEDI** [themeum/tutor#45]
(1) What is the name of the PHP file where the instructor uploads the video to the "Topic"? example in the image below:
![bbb](https://user-images.githubusercontent.com/40426447/106147244-508c1d00-6180-11eb-9960-2e56672ef4d3.png)

2) Can I change the language of the plugin to Hebrew? Can I translate any field by myself?

**Comment by jayedul** [comment]
**Question: 1**

WP core media manager is used for video file uploading. Alternatively you could use absolute video URL from external sources like Youtube, Vimeo etc. 
Tutor LMS just saves the video info as meta data. Here is the file location.
 
File: ~/wp-content/plugins/tutor/classes/Lesson.php
Line: 86-92
Version: 1.8.3

Line number might be changed in future versions.

**Question: 2**

Tutor LMS supports Hebrew language.
https://he.wordpress.org/plugins/search/tutor-lms/
https://translate.wordpress.org/locale/he/default/wp-plugins/tutor/
