### ISSUE TITLE
tutor lms course setting difficulty level metabox

### ISSUE THREAD

**Issue by Ayan008** [themeum/tutor#46]
Hi,
I want to add a more difficulty level here
![image](https://user-images.githubusercontent.com/52524842/106432386-d9fd6100-6498-11eb-947f-afc2eab6060b.png)
can you please tell me where i could find the php code of this meta box?

**Comment by jayedul** [comment]
You could use **tutor_course_level** filter hook to add or remove difficulty levels.

```
add_filter( 'tutor_course_level', function( $levels ) {
	$levels['custom_level'] = __( 'Custom Level', 'text-domain' );
	return $levels;
} );
```

**Comment by Ayan008** [comment]
Hi, 
can you please help me again?
I need to change this button text
![image](https://user-images.githubusercontent.com/52524842/109478690-c3502700-7aa3-11eb-8411-fc5410ea6b7f.png)
