### ISSUE TITLE
 Instructors profile photo issue (Over Wordpress Admin)

### ISSUE THREAD

**Issue by ecastanedapl** [themeum/tutor#50]
I'm trying to add instructors over WordPress Backend, all works fine except the image for the instructor, never get saved.

I get fixed this behavior by doing these simple modifications.

[PLUGIN FOLDER]/views/metabox/user-profile-fields.php
Line 48 (Fix field name)

From:
`<input type="hidden" name="_tutor_profile_photo_field” value="<?php echo $user_profile_photo; ?>">`
To:
`<input type="hidden" name="_tutor_profile_photo" value="<?php echo $user_profile_photo; ?>">`

[PLUGIN FOLDER]/classes/User.php

Line 109 (Add meta post updater)

From:
```
public function profile_update($user_id){
	$_tutor_profile_job_title = sanitize_text_field(tutor_utils()->avalue_dot('_tutor_profile_job_title', $_POST));
	$_tutor_profile_bio = wp_kses_post(tutor_utils()->avalue_dot('_tutor_profile_bio', $_POST));

	update_user_meta($user_id, '_tutor_profile_job_title', $_tutor_profile_job_title);
	update_user_meta($user_id, '_tutor_profile_bio', $_tutor_profile_bio);
}
```

To:

```
public function profile_update($user_id){
	$_tutor_profile_job_title = sanitize_text_field(tutor_utils()->avalue_dot('_tutor_profile_job_title', $_POST));
	$_tutor_profile_bio = wp_kses_post(tutor_utils()->avalue_dot('_tutor_profile_bio', $_POST));
	$_tutor_profile_image = wp_kses_post(tutor_utils()->avalue_dot('_tutor_profile_photo', $_POST));

	update_user_meta($user_id, '_tutor_profile_job_title', $_tutor_profile_job_title);
	update_user_meta($user_id, '_tutor_profile_bio', $_tutor_profile_bio);
	update_user_meta($user_id, '_tutor_profile_photo', $_tutor_profile_image);
}
```

Please send this update because I made these modifications over the plugin if you send another update with this change I get bugged again.

I have a PRO account.

**Comment by sksaju** [comment]
Hi @ecastanedapl

Thank you so much for noticing this issue. After reviewing your changes, we have merged your code and It will be included in the next release. Thanks
